export type ResourceKey = "customers" | "vehicles" | "appointments" | "services" | "employees" | "parts" | "repair-orders" | "invoices" | "payments" | "notifications" | "bays" | "reports";
export type FieldType = "text" | "textarea" | "number" | "date" | "datetime-local" | "select" | "relation";
export type FieldConfig = {
  name: string;
  label: string;
  type: FieldType;
  required?: boolean;
  options?: { value: string; label: string }[];
  relation?: ResourceKey;
};
export type ResourceConfig = {
  title: string;
  singular: string;
  columns: { key: string; label: string; numeric?: boolean }[];
  fields: FieldConfig[];
  searchFields: string[];
  sortFields: string[];
  defaultSort: string;
  statusOptions?: { value: string; label: string }[];
  dateField?: string;
  exportable?: boolean;
};
const active = [{ value: "ACTIVE", label: "Hoạt động" }, { value: "INACTIVE", label: "Ngừng hoạt động" }];
export const memberTiers = [{ value: "Bronze", label: "Đồng" }, { value: "Silver", label: "Bạc" }, { value: "Gold", label: "Vàng" }, { value: "Platinum", label: "Bạch kim" }, { value: "Diamond", label: "Kim cương" }];
const repairStatuses = [
  ["INTAKE", "Tiếp nhận"], ["WAITING_APPROVAL", "Chờ duyệt báo giá"], ["WAITING_PARTS", "Chờ phụ tùng"], ["REPAIRING", "Đang sửa"], ["QUALITY_CHECK", "Kiểm định"], ["READY_FOR_PICKUP", "Sẵn sàng bàn giao"], ["COMPLETED", "Hoàn tất"], ["CANCELLED", "Đã hủy"],
].map(([value, label]) => ({ value, label }));
const appointmentStatuses = [["PENDING", "Chờ xác nhận"], ["CONFIRMED", "Đã xác nhận"], ["ARRIVED", "Đã đến"], ["IN_PROGRESS", "Đang xử lý"], ["CANCELLED", "Đã hủy"], ["COMPLETED", "Hoàn tất"]].map(([value, label]) => ({ value, label }));
const invoiceStatuses = [["DRAFT", "Nháp"], ["PENDING_APPROVAL", "Chờ duyệt"], ["UNPAID", "Chờ thanh toán"], ["PARTIALLY_PAID", "Thanh toán một phần"], ["PAID", "Đã thanh toán"], ["CANCELLED", "Đã hủy"]].map(([value, label]) => ({ value, label }));
const paymentStatuses = [["PENDING", "Chờ thanh toán"], ["COMPLETED", "Hoàn tất"], ["FAILED", "Thất bại"], ["REFUNDED", "Đã hoàn"]].map(([value, label]) => ({ value, label }));
const vehicleStatuses = [["ACTIVE", "Hoạt động"], ["IN_REPAIR", "Đang sửa"], ["READY", "Sẵn sàng bàn giao"]].map(([value, label]) => ({ value, label }));

export const resourceConfig: Record<ResourceKey, ResourceConfig> = {
  customers: { title: "Khách hàng", singular: "khách hàng", columns: [{ key: "name", label: "Khách hàng" }, { key: "phone", label: "Điện thoại" }, { key: "email", label: "Email" }, { key: "tier", label: "Hạng" }, { key: "repairCount", label: "Lần sửa hoàn tất", numeric: true }, { key: "status", label: "Trạng thái" }], fields: [{ name: "name", label: "Họ và tên", type: "text", required: true }, { name: "phone", label: "Số điện thoại", type: "text" }, { name: "email", label: "Email", type: "text" }, { name: "tier", label: "Hạng thành viên", type: "select", options: memberTiers }, { name: "address", label: "Địa chỉ", type: "text" }, { name: "status", label: "Trạng thái", type: "select", options: active }], searchFields: ["name", "phone", "email"], sortFields: ["name", "createdAt", "updatedAt"], defaultSort: "createdAt", statusOptions: active, exportable: true },
  vehicles: { title: "Phương tiện", singular: "xe", columns: [{ key: "plate", label: "Biển số" }, { key: "name", label: "Phương tiện" }, { key: "customer.name", label: "Chủ xe" }, { key: "odometerKm", label: "ODO (km)", numeric: true }, { key: "status", label: "Trạng thái" }], fields: [{ name: "plate", label: "Biển số", type: "text", required: true }, { name: "name", label: "Tên xe", type: "text", required: true }, { name: "customerId", label: "Chủ xe", type: "relation", relation: "customers" }, { name: "vin", label: "VIN", type: "text" }, { name: "odometerKm", label: "ODO (km)", type: "number" }, { name: "warranty", label: "Bảo hành", type: "text" }, { name: "status", label: "Trạng thái", type: "select", options: vehicleStatuses }], searchFields: ["plate", "name", "vin", "customer.name"], sortFields: ["plate", "name", "createdAt"], defaultSort: "createdAt", statusOptions: vehicleStatuses, exportable: true },
  appointments: { title: "Lịch hẹn", singular: "lịch hẹn", columns: [{ key: "code", label: "Mã hẹn" }, { key: "customer.name", label: "Khách hàng" }, { key: "vehicle.plate", label: "Biển số" }, { key: "service.title", label: "Dịch vụ" }, { key: "startsAt", label: "Thời gian" }, { key: "status", label: "Trạng thái" }], fields: [{ name: "code", label: "Mã hẹn", type: "text", required: true }, { name: "customerId", label: "Khách hàng", type: "relation", relation: "customers", required: true }, { name: "vehicleId", label: "Phương tiện", type: "relation", relation: "vehicles", required: true }, { name: "serviceId", label: "Dịch vụ", type: "relation", relation: "services" }, { name: "startsAt", label: "Ngày giờ hẹn", type: "datetime-local", required: true }, { name: "endsAt", label: "Giờ kết thúc", type: "datetime-local" }, { name: "notes", label: "Yêu cầu thêm", type: "textarea" }, { name: "status", label: "Trạng thái", type: "select", options: appointmentStatuses }], searchFields: ["code", "customer.name", "vehicle.plate", "service.title"], sortFields: ["startsAt", "code", "createdAt"], defaultSort: "startsAt", statusOptions: appointmentStatuses, dateField: "startsAt", exportable: true },
  services: { title: "Dịch vụ", singular: "dịch vụ", columns: [{ key: "code", label: "Mã" }, { key: "title", label: "Tên dịch vụ" }, { key: "durationMinutes", label: "Phút", numeric: true }, { key: "price", label: "Giá", numeric: true }, { key: "status", label: "Trạng thái" }], fields: [{ name: "code", label: "Mã dịch vụ", type: "text", required: true }, { name: "title", label: "Tên dịch vụ", type: "text", required: true }, { name: "description", label: "Mô tả", type: "textarea" }, { name: "durationMinutes", label: "Thời lượng (phút)", type: "number", required: true }, { name: "price", label: "Giá (VND)", type: "number", required: true }, { name: "status", label: "Trạng thái", type: "select", options: active }], searchFields: ["code", "title"], sortFields: ["code", "title", "price", "createdAt"], defaultSort: "createdAt", statusOptions: active },
  employees: { title: "Nhân viên", singular: "nhân viên", columns: [{ key: "code", label: "Mã" }, { key: "name", label: "Nhân sự" }, { key: "email", label: "Email đăng nhập" }, { key: "specialty", label: "Chuyên môn" }, { key: "status", label: "Trạng thái" }], fields: [{ name: "code", label: "Mã nhân viên", type: "text", required: true }, { name: "name", label: "Họ và tên", type: "text", required: true }, { name: "email", label: "Email đăng nhập", type: "text", required: true }, { name: "specialty", label: "Chuyên môn", type: "text" }, { name: "role", label: "Vai trò", type: "text" }, { name: "shiftStart", label: "Bắt đầu ca", type: "text" }, { name: "shiftEnd", label: "Kết thúc ca", type: "text" }, { name: "status", label: "Trạng thái", type: "select", options: active }], searchFields: ["code", "name", "email", "specialty"], sortFields: ["code", "name", "createdAt"], defaultSort: "createdAt", statusOptions: active },
  parts: { title: "Kho phụ tùng", singular: "phụ tùng", columns: [{ key: "sku", label: "SKU" }, { key: "name", label: "Phụ tùng" }, { key: "brand", label: "Thương hiệu" }, { key: "location", label: "Vị trí" }, { key: "price", label: "Giá bán", numeric: true }, { key: "stockQty", label: "Tồn", numeric: true }, { key: "minStock", label: "Tối thiểu", numeric: true }], fields: [{ name: "sku", label: "SKU", type: "text", required: true }, { name: "name", label: "Tên phụ tùng", type: "text", required: true }, { name: "brand", label: "Thương hiệu", type: "text" }, { name: "location", label: "Vị trí", type: "text" }, { name: "cost", label: "Giá nhập", type: "number", required: true }, { name: "price", label: "Giá bán", type: "number", required: true }, { name: "stockQty", label: "Số lượng tồn", type: "number", required: true }, { name: "minStock", label: "Mức tối thiểu", type: "number", required: true }, { name: "unit", label: "Đơn vị", type: "text", required: true }], searchFields: ["sku", "name", "brand"], sortFields: ["sku", "name", "stockQty", "price", "createdAt"], defaultSort: "createdAt", exportable: true },
  "repair-orders": { title: "Phiếu sửa chữa", singular: "phiếu sửa chữa", columns: [{ key: "code", label: "Mã phiếu" }, { key: "vehicle.plate", label: "Biển số" }, { key: "customer.name", label: "Khách hàng" }, { key: "technician.name", label: "KTV" }, { key: "scheduledAt", label: "Thời gian" }, { key: "status", label: "Trạng thái" }], fields: [{ name: "code", label: "Mã phiếu", type: "text", required: true }, { name: "customerId", label: "Khách hàng", type: "relation", relation: "customers", required: true }, { name: "vehicleId", label: "Phương tiện", type: "relation", relation: "vehicles", required: true }, { name: "advisorId", label: "Cố vấn", type: "relation", relation: "employees" }, { name: "technicianId", label: "Kỹ thuật viên", type: "relation", relation: "employees" }, { name: "scheduledAt", label: "Thời gian", type: "datetime-local" }, { name: "bayCode", label: "Khoang", type: "text" }, { name: "odometerKm", label: "ODO (km)", type: "number" }, { name: "diagnosis", label: "Chẩn đoán", type: "textarea" }, { name: "status", label: "Trạng thái", type: "select", options: repairStatuses }], searchFields: ["code", "customer.name", "vehicle.plate"], sortFields: ["scheduledAt", "code", "createdAt", "status"], defaultSort: "createdAt", statusOptions: repairStatuses, dateField: "scheduledAt", exportable: true },
  invoices: { title: "Hóa đơn", singular: "hóa đơn", columns: [{ key: "code", label: "Mã chứng từ" }, { key: "customer.name", label: "Khách hàng" }, { key: "vehicle.plate", label: "Biển số" }, { key: "issuedAt", label: "Ngày" }, { key: "subtotal", label: "Tạm tính", numeric: true }, { key: "discount", label: "Ưu đãi hội viên", numeric: true }, { key: "total", label: "Tổng tiền", numeric: true }, { key: "paymentMethodLabel", label: "Thanh toán qua" }, { key: "latestPaidAt", label: "Thanh toán lúc" }, { key: "status", label: "Trạng thái" }], fields: [{ name: "code", label: "Mã chứng từ", type: "text", required: true }, { name: "customerId", label: "Khách hàng", type: "relation", relation: "customers", required: true }, { name: "vehicleId", label: "Phương tiện", type: "relation", relation: "vehicles" }, { name: "repairOrderId", label: "Phiếu sửa chữa", type: "relation", relation: "repair-orders" }, { name: "issuedAt", label: "Ngày phát hành", type: "date" }, { name: "subtotal", label: "Tạm tính (VND)", type: "number", required: true }, { name: "tax", label: "Thuế (VND)", type: "number" }, { name: "status", label: "Trạng thái", type: "select", options: invoiceStatuses }], searchFields: ["code", "customer.name", "vehicle.plate"], sortFields: ["issuedAt", "code", "total", "createdAt"], defaultSort: "issuedAt", statusOptions: invoiceStatuses, dateField: "issuedAt", exportable: true },
  payments: { title: "Thanh toán", singular: "thanh toán", columns: [{ key: "code", label: "Mã" }, { key: "invoice.code", label: "Hóa đơn" }, { key: "amount", label: "Số tiền", numeric: true }, { key: "method", label: "Phương thức" }, { key: "paidAt", label: "Ngày thanh toán" }, { key: "status", label: "Trạng thái" }], fields: [{ name: "code", label: "Mã thanh toán", type: "text", required: true }, { name: "invoiceId", label: "Hóa đơn", type: "relation", relation: "invoices", required: true }, { name: "amount", label: "Số tiền", type: "number", required: true }, { name: "method", label: "Phương thức", type: "select", options: [["CASH", "Tiền mặt"], ["BANK_TRANSFER", "Chuyển khoản"], ["CARD", "Thẻ"], ["OTHER", "Khác"]].map(([value, label]) => ({ value, label })) }, { name: "paidAt", label: "Ngày thanh toán", type: "datetime-local" }, { name: "notes", label: "Ghi chú", type: "textarea" }, { name: "status", label: "Trạng thái", type: "select", options: paymentStatuses }], searchFields: ["code", "invoice.code"], sortFields: ["paidAt", "amount", "createdAt"], defaultSort: "createdAt", statusOptions: paymentStatuses, dateField: "paidAt", exportable: true },
  notifications: { title: "Thông báo", singular: "thông báo", columns: [{ key: "title", label: "Tiêu đề" }, { key: "type", label: "Loại" }, { key: "createdAt", label: "Tạo lúc" }, { key: "readAt", label: "Đã đọc" }], fields: [{ name: "title", label: "Tiêu đề", type: "text", required: true }, { name: "body", label: "Nội dung", type: "textarea" }, { name: "type", label: "Loại", type: "select", options: [["INFO", "Thông tin"], ["WARNING", "Cảnh báo"], ["ERROR", "Lỗi"], ["SUCCESS", "Thành công"]].map(([value, label]) => ({ value, label })) }, { name: "employeeId", label: "Nhân viên nhận", type: "relation", relation: "employees" }, { name: "readAt", label: "Đã đọc lúc", type: "datetime-local" }], searchFields: ["title", "body"], sortFields: ["createdAt", "readAt", "title"], defaultSort: "createdAt" },
  bays: { title: "Khoang sửa chữa", singular: "khoang", columns: [{ key: "code", label: "Khoang" }, { key: "vehicle.plate", label: "Biển số" }, { key: "employee.name", label: "Kỹ thuật viên" }, { key: "statusText", label: "Trạng thái" }, { key: "progressNote", label: "Báo cáo mới nhất" }], fields: [{ name: "code", label: "Mã khoang", type: "text", required: true }, { name: "vehicleId", label: "Phương tiện", type: "relation", relation: "vehicles" }, { name: "employeeId", label: "Kỹ thuật viên", type: "relation", relation: "employees" }, { name: "statusText", label: "Trạng thái", type: "text" }, { name: "progressNote", label: "Báo cáo mới nhất", type: "textarea" }, { name: "reportedAt", label: "Thời điểm báo cáo", type: "datetime-local" }], searchFields: ["code", "vehicle.plate", "employee.name", "progressNote"], sortFields: ["code", "createdAt"], defaultSort: "code" },
  reports: { title: "Báo cáo doanh thu", singular: "báo cáo", columns: [{ key: "periodStart", label: "Kỳ báo cáo" }, { key: "revenue", label: "Doanh thu", numeric: true }, { key: "cost", label: "Chi phí", numeric: true }, { key: "profit", label: "Lợi nhuận", numeric: true }, { key: "status", label: "Trạng thái" }], fields: [{ name: "periodStart", label: "Kỳ báo cáo", type: "date", required: true }, { name: "revenue", label: "Doanh thu", type: "number", required: true }, { name: "cost", label: "Chi phí", type: "number", required: true }, { name: "profit", label: "Lợi nhuận", type: "number", required: true }, { name: "status", label: "Trạng thái", type: "select", options: active }], searchFields: [], sortFields: ["periodStart", "revenue", "profit"], defaultSort: "periodStart", statusOptions: active, dateField: "periodStart", exportable: true },
};
export const resourceKeys = Object.keys(resourceConfig) as ResourceKey[];
export function isResourceKey(value: string): value is ResourceKey { return Object.prototype.hasOwnProperty.call(resourceConfig, value); }
export function fieldValue(record: Record<string, unknown>, path: string): unknown { return path.split(".").reduce<unknown>((value, key) => value && typeof value === "object" ? (value as Record<string, unknown>)[key] : undefined, record); }
export function displayValue(value: unknown, key: string, config?: ResourceConfig): string {
  if (value == null) return "—";
  if (key === "progressNote") return String(value).length > 90 ? `${String(value).slice(0, 90)}…` : String(value);
  if (key === "tier") return memberTiers.find((tier) => tier.value === value)?.label ?? String(value);
  if (key === "status" && config?.statusOptions) return config.statusOptions.find((option) => option.value === value)?.label ?? String(value);
  if (typeof value === "boolean") return value ? "Có" : "Không";
  if (key.endsWith("At") || key === "periodStart") { const date = new Date(String(value)); return Number.isNaN(date.getTime()) ? String(value) : new Intl.DateTimeFormat("vi-VN", { dateStyle: "short", ...(key === "periodStart" ? {} : { timeStyle: "short" }) }).format(date); }
  if (typeof value === "number" || /^\d+(\.\d+)?$/.test(String(value))) return key.match(/price|cost|total|amount|revenue|profit|discount|tax/i) ? `${new Intl.NumberFormat("vi-VN").format(Number(value))} ₫` : new Intl.NumberFormat("vi-VN").format(Number(value));
  return String(value);
}
