import Link from "next/link";
import { ArrowRight, ClipboardList } from "lucide-react";
import { getDashboardData } from "@/server/services/dashboard-service";
import { Status } from "@/components/ui/AppUi";
import { displayValue, resourceConfig } from "@/lib/resource-config";
import { statusTone } from "@/lib/status";

function Heading({ title, href }: { title: string; href: string }) {
  return <div className="flex items-center justify-between border-b px-4 py-3"><h2 className="text-sm font-semibold">{title}</h2><Link href={href} className="admin-text-link flex items-center gap-1 text-xs">Xem tất cả <ArrowRight size={13} /></Link></div>;
}
function Empty({ text }: { text: string }) { return <p className="px-4 py-6 text-sm text-[var(--admin-muted)]">{text}</p>; }
export async function DashboardPage() {
  let data;
  try { data = await getDashboardData(); } catch (error) { return <div role="alert" className="admin-panel p-6 text-sm"><h1 className="admin-page-title">Tổng quan</h1><p className="mt-3 text-red-700">{error instanceof Error ? error.message : "Không tải được dữ liệu."}</p></div>; }
  const money = new Intl.NumberFormat("vi-VN").format(data.revenue) + " ₫";
  const metrics = [
    ["Lịch hẹn hôm nay", data.appointmentsToday, "/admin/appointments"], ["Xe đang sửa", data.repairing, "/admin/repair-orders"],
    ["Chờ duyệt báo giá", data.waitingApproval, "/admin/repair-orders"], ["Sẵn sàng bàn giao", data.ready, "/admin/repair-orders"],
    ["Doanh thu hôm nay", money, "/admin/invoices"], ["Công việc quá hạn", data.overdue, "/admin/repair-orders"],
  ] as const;
  return <div className="mx-auto max-w-[1500px] space-y-5"><div className="flex items-center justify-between gap-3"><h1 className="admin-page-title">Tổng quan</h1><Link href="/admin/repair-orders" className="btn btn-soft"><ClipboardList size={15} />Phiếu sửa chữa</Link></div>
    <section aria-label="Chỉ số vận hành" className="admin-metrics grid grid-cols-2 border sm:grid-cols-3 xl:grid-cols-6">{metrics.map(([label, value, href]) => <Link key={label} href={href} className="admin-metric border-b p-4 sm:border-b-0"><span className="block text-xs text-[var(--admin-muted)]">{label}</span><strong className="mt-2 block text-[25px] font-semibold leading-none">{value}</strong></Link>)}</section>
    <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1.7fr)_minmax(300px,1fr)]"><div className="min-w-0 space-y-5"><section className="admin-panel overflow-hidden"><Heading title="Lịch hẹn hôm nay" href="/admin/appointments" />{data.appointments.length ? <div className="overflow-x-auto"><table className="app-table admin-table"><thead><tr><th>Giờ</th><th>Biển số</th><th>Khách hàng</th><th>Dịch vụ</th><th>Trạng thái</th></tr></thead><tbody>{data.appointments.map((item) => <tr key={item.id}><td>{new Intl.DateTimeFormat("vi-VN", { hour: "2-digit", minute: "2-digit", timeZone: "Asia/Ho_Chi_Minh" }).format(item.startsAt)}</td><td>{item.vehicle.plate}</td><td>{item.customer.name}</td><td>{item.service?.title ?? "—"}</td><td><Status tone={statusTone(item.status)}>{displayValue(item.status, "status", resourceConfig.appointments)}</Status></td></tr>)}</tbody></table></div> : <Empty text="Không có lịch hẹn hôm nay." />}</section><section className="admin-panel overflow-hidden"><Heading title="Phiếu đang xử lý" href="/admin/repair-orders" />{data.orders.length ? <div className="overflow-x-auto"><table className="app-table admin-table"><thead><tr><th>Mã phiếu</th><th>Biển số</th><th>Khách hàng</th><th>Kỹ thuật viên</th><th>Trạng thái</th></tr></thead><tbody>{data.orders.map((item) => <tr key={item.id}><td><Link className="admin-text-link" href={`/admin/repair-orders/${item.id}`}>{item.code}</Link></td><td>{item.vehicle.plate}</td><td>{item.customer.name}</td><td>{item.technician?.name ?? "—"}</td><td><Status tone={statusTone(item.status)}>{displayValue(item.status, "status", resourceConfig["repair-orders"])}</Status></td></tr>)}</tbody></table></div> : <Empty text="Không có phiếu đang xử lý." />}</section></div>
    <div className="min-w-0 space-y-5"><section className="admin-panel"><Heading title="Sẵn sàng bàn giao" href="/admin/repair-orders" />{data.readyOrders.length ? <div className="divide-y">{data.readyOrders.map((item) => <Link key={item.id} href={`/admin/repair-orders/${item.id}`} className="block px-4 py-3 text-sm hover:bg-slate-50"><strong>{item.vehicle.plate}</strong><span className="ml-2 text-[var(--admin-muted)]">{item.customer.name}</span></Link>)}</div> : <Empty text="Chưa có xe chờ bàn giao." />}</section><section className="admin-panel"><Heading title="Tồn kho cần kiểm tra" href="/admin/inventory" />{data.lowStock.length ? <div className="divide-y">{data.lowStock.map((item) => <div key={item.id} className="flex justify-between gap-3 px-4 py-3 text-sm"><span>{item.name}</span><span className="font-medium">{item.stockQty} / {item.minStock}</span></div>)}</div> : <Empty text="Tồn kho đang đủ mức tối thiểu." />}</section><section className="admin-panel"><Heading title="Thông báo gần đây" href="/admin/notifications" />{data.notifications.length ? <div className="divide-y">{data.notifications.map((item) => <div key={item.id} className="px-4 py-3 text-sm"><p className="font-medium">{item.title}</p>{item.body && <p className="mt-1 line-clamp-2 text-xs text-[var(--admin-muted)]">{item.body}</p>}<time className="mt-1 block text-xs text-[var(--admin-muted)]" dateTime={item.createdAt.toISOString()}>{new Intl.DateTimeFormat("vi-VN", { dateStyle: "short", timeStyle: "short", timeZone: "Asia/Ho_Chi_Minh" }).format(item.createdAt)}</time></div>)}</div> : <Empty text="Chưa có thông báo." />}</section></div></div></div>;
}
