import Link from "next/link";
import { ArrowRight, CalendarDays, ChevronLeft, ChevronRight, ClipboardList } from "lucide-react";
import { getDashboardData } from "@/server/services/dashboard-service";
import { DashboardCharts } from "@/components/admin/DashboardCharts";
import { adjacentPeriodDate, resolveDashboardPeriod, type DashboardPeriodKind } from "@/lib/dashboard-period";
import { Status } from "@/components/ui/AppUi";
import { displayValue, resourceConfig } from "@/lib/resource-config";
import { statusTone } from "@/lib/status";

function Heading({ title, href }: { title: string; href: string }) {
  return <div className="flex items-center justify-between border-b px-4 py-3"><h2 className="text-sm font-semibold">{title}</h2><Link href={href} className="admin-text-link flex items-center gap-1 text-xs">Xem tất cả <ArrowRight size={13} /></Link></div>;
}
function Empty({ text }: { text: string }) { return <p className="px-4 py-6 text-sm text-[var(--admin-muted)]">{text}</p>; }
const periods: { value: DashboardPeriodKind; label: string }[] = [
  { value: "day", label: "Ngày" }, { value: "week", label: "Tuần" }, { value: "month", label: "Tháng" },
  { value: "quarter", label: "Quý" }, { value: "year", label: "Năm" },
];
const moneyValue = (value: number) => `${new Intl.NumberFormat("vi-VN", { maximumFractionDigits: 0 }).format(value)} ₫`;
export async function DashboardPage({ periodValue, dateValue }: { periodValue?: string; dateValue?: string }) {
  const selectedPeriod = resolveDashboardPeriod(periodValue, dateValue);
  let data;
  try { data = await getDashboardData(selectedPeriod); } catch (error) { return <div role="alert" className="admin-panel p-6 text-sm"><h1 className="admin-page-title">Tổng quan</h1><p className="mt-3 text-red-700">{error instanceof Error ? error.message : "Không tải được dữ liệu."}</p></div>; }
  const periodHref = (period: DashboardPeriodKind, date: string) => `/admin?period=${period}&date=${date}`;
  const summaryMetrics = [
    { label: "Doanh thu đã thu", value: moneyValue(data.periodSummary.revenue), detail: "Thanh toán hoàn tất" },
    { label: "Lượt thanh toán", value: data.periodSummary.payments, detail: "Giao dịch trong kỳ" },
    { label: "Lịch hẹn", value: data.periodSummary.appointments, detail: "Theo thời gian hẹn" },
    { label: "Phiếu sửa chữa mới", value: data.periodSummary.orders, detail: "Theo ngày tạo phiếu" },
  ];
  const money = new Intl.NumberFormat("vi-VN").format(data.revenue) + " ₫";
  const metrics = [
    ["Lịch hẹn hôm nay", data.appointmentsToday, "/admin/appointments"], ["Xe đang sửa", data.repairing, "/admin/repair-orders"],
    ["Chờ duyệt báo giá", data.waitingApproval, "/admin/repair-orders"], ["Sẵn sàng bàn giao", data.ready, "/admin/repair-orders"],
    ["Doanh thu hôm nay", money, "/admin/invoices"], ["Công việc quá hạn", data.overdue, "/admin/repair-orders"],
  ] as const;
  return <div className="mx-auto max-w-[1500px] space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="admin-page-title">Tổng quan</h1><p className="mt-1 text-xs text-[var(--admin-muted)]">Doanh thu và hoạt động của gara theo thời gian</p></div><Link href="/admin/repair-orders" className="btn btn-soft"><ClipboardList size={15} />Phiếu sửa chữa</Link></div>
    <section aria-labelledby="period-heading" className="admin-panel overflow-hidden">
      <div className="flex flex-col gap-4 p-4 sm:p-5 lg:flex-row lg:items-end lg:justify-between">
        <div><h2 id="period-heading" className="text-sm font-semibold text-slate-900">Thống kê theo kỳ</h2><p className="mt-1 text-xs text-[var(--admin-muted)]">Chọn ngày tham chiếu và khoảng thời gian muốn xem.</p>
          <nav aria-label="Khoảng thời gian thống kê" className="mt-4 inline-flex max-w-full flex-wrap gap-1 rounded-lg bg-slate-100 p-1">{periods.map(({ value, label }) => <Link key={value} href={periodHref(value, selectedPeriod.date)} aria-current={selectedPeriod.kind === value ? "page" : undefined} className={`rounded-md px-3 py-2 text-xs font-semibold transition-colors ${selectedPeriod.kind === value ? "bg-white text-[var(--admin-primary)] shadow-sm" : "text-slate-600 hover:bg-white/70 hover:text-slate-900"}`}>{label}</Link>)}</nav>
        </div>
        <form action="/admin" method="get" className="flex flex-wrap items-end gap-2"><input type="hidden" name="period" value={selectedPeriod.kind} /><label className="text-xs font-medium text-[var(--admin-muted)]"><span className="mb-1.5 block">Ngày tham chiếu</span><span className="relative block"><CalendarDays size={15} className="pointer-events-none absolute left-3 top-2.5 text-[var(--admin-muted)]" /><input type="date" name="date" defaultValue={selectedPeriod.date} className="field w-[170px] pl-9!" /></span></label><button type="submit" className="btn btn-primary">Xem thống kê</button></form>
      </div>
      <div className="flex flex-wrap items-center justify-between gap-3 border-t bg-slate-50/70 px-4 py-3 sm:px-5"><div><p className="text-[11px] font-semibold uppercase tracking-[0.09em] text-[var(--admin-muted)]">Kỳ đang xem</p><p className="mt-0.5 text-sm font-semibold text-slate-900">{selectedPeriod.label}</p></div><div className="flex items-center gap-1"><Link aria-label="Kỳ trước" href={periodHref(selectedPeriod.kind, adjacentPeriodDate(selectedPeriod, -1))} className="btn btn-soft px-2!"><ChevronLeft size={16} /></Link><Link aria-label="Kỳ tiếp theo" href={periodHref(selectedPeriod.kind, adjacentPeriodDate(selectedPeriod, 1))} className="btn btn-soft px-2!"><ChevronRight size={16} /></Link></div></div>
    </section>
    <section aria-label={`Chỉ số ${selectedPeriod.label}`} className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{summaryMetrics.map((metric) => <div key={metric.label} className="admin-panel min-w-0 p-4"><span className="block text-xs font-medium text-[var(--admin-muted)]">{metric.label}</span><strong className="mt-3 block truncate text-[clamp(1.25rem,2vw,1.7rem)] font-semibold leading-none tracking-tight text-slate-900" title={String(metric.value)}>{metric.value}</strong><span className="mt-3 block text-[11px] text-[var(--admin-muted)]">{metric.detail}</span></div>)}</section>
    <section aria-labelledby="charts-heading" className="space-y-3"><div className="flex flex-wrap items-baseline justify-between gap-2"><h2 id="charts-heading" className="text-sm font-semibold text-slate-900">Biểu đồ {selectedPeriod.label.toLowerCase()}</h2><span className="text-xs text-[var(--admin-muted)]">Múi giờ Việt Nam (UTC+7)</span></div><DashboardCharts points={data.series} /></section>
    <section aria-labelledby="live-heading" className="space-y-3"><div><h2 id="live-heading" className="text-sm font-semibold text-slate-900">Tình hình hiện tại</h2><p className="mt-1 text-xs text-[var(--admin-muted)]">Các chỉ số vận hành và việc cần xử lý hôm nay</p></div><div className="admin-metrics grid grid-cols-2 border sm:grid-cols-3 xl:grid-cols-6">{metrics.map(([label, value, href]) => <Link key={label} href={href} className="admin-metric border-b p-4 sm:border-b-0"><span className="block text-xs text-[var(--admin-muted)]">{label}</span><strong className="mt-2 block text-[25px] font-semibold leading-none">{value}</strong></Link>)}</div></section>
    <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1.7fr)_minmax(300px,1fr)]"><div className="min-w-0 space-y-5"><section className="admin-panel overflow-hidden"><Heading title="Lịch hẹn hôm nay" href="/admin/appointments" />{data.appointments.length ? <div className="overflow-x-auto"><table className="app-table admin-table"><thead><tr><th>Giờ</th><th>Biển số</th><th>Khách hàng</th><th>Dịch vụ</th><th>Trạng thái</th></tr></thead><tbody>{data.appointments.map((item) => <tr key={item.id}><td>{new Intl.DateTimeFormat("vi-VN", { hour: "2-digit", minute: "2-digit", timeZone: "Asia/Ho_Chi_Minh" }).format(item.startsAt)}</td><td>{item.vehicle.plate}</td><td>{item.customer.name}</td><td>{item.service?.title ?? "—"}</td><td><Status tone={statusTone(item.status)}>{displayValue(item.status, "status", resourceConfig.appointments)}</Status></td></tr>)}</tbody></table></div> : <Empty text="Không có lịch hẹn hôm nay." />}</section><section className="admin-panel overflow-hidden"><Heading title="Phiếu đang xử lý" href="/admin/repair-orders" />{data.orders.length ? <div className="overflow-x-auto"><table className="app-table admin-table"><thead><tr><th>Mã phiếu</th><th>Biển số</th><th>Khách hàng</th><th>Kỹ thuật viên</th><th>Trạng thái</th></tr></thead><tbody>{data.orders.map((item) => <tr key={item.id}><td><Link className="admin-text-link" href={`/admin/repair-orders/${item.id}`}>{item.code}</Link></td><td>{item.vehicle.plate}</td><td>{item.customer.name}</td><td>{item.technician?.name ?? "—"}</td><td><Status tone={statusTone(item.status)}>{displayValue(item.status, "status", resourceConfig["repair-orders"])}</Status></td></tr>)}</tbody></table></div> : <Empty text="Không có phiếu đang xử lý." />}</section></div>
    <div className="min-w-0 space-y-5"><section className="admin-panel"><Heading title="Sẵn sàng bàn giao" href="/admin/repair-orders" />{data.readyOrders.length ? <div className="divide-y">{data.readyOrders.map((item) => <Link key={item.id} href={`/admin/repair-orders/${item.id}`} className="block px-4 py-3 text-sm hover:bg-slate-50"><strong>{item.vehicle.plate}</strong><span className="ml-2 text-[var(--admin-muted)]">{item.customer.name}</span></Link>)}</div> : <Empty text="Chưa có xe chờ bàn giao." />}</section><section className="admin-panel"><Heading title="Tồn kho cần kiểm tra" href="/admin/inventory" />{data.lowStock.length ? <div className="divide-y">{data.lowStock.map((item) => <div key={item.id} className="flex justify-between gap-3 px-4 py-3 text-sm"><span>{item.name}</span><span className="font-medium">{item.stockQty} / {item.minStock}</span></div>)}</div> : <Empty text="Tồn kho đang đủ mức tối thiểu." />}</section><section className="admin-panel"><Heading title="Thông báo gần đây" href="/admin/notifications" />{data.notifications.length ? <div className="divide-y">{data.notifications.map((item) => <div key={item.id} className="px-4 py-3 text-sm"><p className="font-medium">{item.title}</p>{item.body && <p className="mt-1 line-clamp-2 text-xs text-[var(--admin-muted)]">{item.body}</p>}<time className="mt-1 block text-xs text-[var(--admin-muted)]" dateTime={item.createdAt.toISOString()}>{new Intl.DateTimeFormat("vi-VN", { dateStyle: "short", timeStyle: "short", timeZone: "Asia/Ho_Chi_Minh" }).format(item.createdAt)}</time></div>)}</div> : <Empty text="Chưa có thông báo." />}</section></div></div></div>;
}
