"use client";

import { useState } from "react";
import { Search } from "lucide-react";
import type { InventoryItem } from "@/types";
import { AdminEmptyState } from "@/components/admin/AdminStates";

export function InventoryTable({ items }: { items: InventoryItem[] }) {
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("all");
  const filtered = items.filter((item) => `${item.sku} ${item.name} ${item.brand}`.toLocaleLowerCase("vi").includes(query.trim().toLocaleLowerCase("vi")) && (filter === "all" || Boolean(item.critical)));
  return <section className="admin-panel overflow-hidden" aria-label="Danh sách phụ tùng"><div className="flex flex-col gap-3 border-b px-4 py-3 md:flex-row md:items-center md:justify-between"><div><h2 className="text-sm font-semibold">Phụ tùng</h2><p className="mt-0.5 text-xs text-[var(--admin-muted)]" aria-live="polite">{filtered.length} / {items.length} mã</p></div><div className="flex flex-col gap-2 sm:flex-row"><div className="relative"><Search size={15} className="pointer-events-none absolute left-3 top-2.5 text-[var(--admin-muted)]" /><input aria-label="Tìm mã SKU hoặc phụ tùng" className="field w-full pl-9! sm:w-60" placeholder="Mã SKU hoặc phụ tùng" value={query} onChange={(event) => setQuery(event.target.value)} /></div><select aria-label="Lọc tồn kho" className="field" value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">Tất cả tồn kho</option><option value="critical">Dưới mức tối thiểu</option></select></div></div>{filtered.length ? <><div className="hidden overflow-x-auto md:block" tabIndex={0} role="region" aria-label="Bảng phụ tùng"><table className="app-table admin-table"><thead><tr><th scope="col">Mã / tên phụ tùng</th><th scope="col">Thương hiệu</th><th scope="col">Vị trí</th><th scope="col" className="text-right!">Giá nhập</th><th scope="col" className="text-right!">Giá bán</th><th scope="col" className="text-right!">Tồn / tối thiểu</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.sku}><td><span className="font-semibold">{item.name}</span><span className="mt-0.5 block text-xs text-[var(--admin-muted)]">{item.sku}</span></td><td>{item.brand}</td><td>{item.location}</td><td className="text-right! tabular-nums">{item.cost}</td><td className="text-right! font-medium tabular-nums">{item.price}</td><td className={`text-right! font-medium tabular-nums ${item.critical ? "admin-stock-critical" : ""}`}>{item.stock}</td></tr>)}</tbody></table></div><div className="divide-y md:hidden">{filtered.map((item) => <div key={item.sku} className="px-4 py-3"><div className="flex justify-between gap-3"><div className="min-w-0"><p className="text-sm font-semibold">{item.name}</p><p className="mt-0.5 text-xs text-[var(--admin-muted)]">{item.sku} · {item.location}</p></div><span className={`shrink-0 text-xs font-semibold ${item.critical ? "admin-stock-critical" : ""}`}>{item.stock}</span></div><p className="mt-2 text-xs">Giá bán: <strong>{item.price}</strong></p></div>)}</div></> : <AdminEmptyState title="Không tìm thấy phụ tùng" description="Thử mã SKU hoặc bỏ bộ lọc tồn kho." />}<div className="border-t px-4 py-2.5 text-xs text-[var(--admin-muted)]">{filtered.length} / {items.length} mã phụ tùng</div></section>;
}
